services:
  - type: web
    name: anthropie-music
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SUDO_USERS
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: anthropie_music
      - key: PYTHONUNBUFFERED
        value: "1"
